"""Add topic to LearnedWord

Revision ID: 245b323e7838
Revises: a59b8f8dfa31
Create Date: 2024-12-31 22:01:45.303964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245b323e7838'
down_revision: Union[str, None] = 'a59b8f8dfa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_words', sa.Column('topic', sa.String(), nullable=True))
    op.alter_column('learned_words', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'learned_words', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learned_words', type_='foreignkey')
    op.alter_column('learned_words', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('learned_words', 'topic')
    # ### end Alembic commands ###
